### ISSUE TITLE
Error migrating content: "Undefined index: fields"

### ISSUE THREAD

**Issue by emarthinsen** [Firstborn/Craft-Migration-Manager#16]
Hi. I'm trying to migrate some content. I was able to create the migration, but when I try to apply it, I get this error:

```
A fatal error has occurred:

Status: Internal Server Error

Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_ migration: Undefined index: fields"}
```

**Comment by fb-derrick-grigg** [comment]
Any extra details in the error log?

**Comment by emarthinsen** [comment]
Only a little bit more. I'm trawling through the `web.log` file to see if there is some useful info. Here's something that might help:

```
Next craft\errors\MigrationException: An error occurred while executing the "craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_ migration: Undefined index: fields in /var/app/vendor/craftcms/cms/src/db/MigrationManager.php:260
Stack trace:
#0 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_piconium_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_piconium_support_revision_history_piconium_support_))
#1 /var/app/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#2 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#3 /var/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /var/app/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('migrations', Array)
#6 /var/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#7 /var/app/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('migrationmanage...', Array)
#8 /var/app/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('migrationmanage...', Array)
#9 /var/app/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/app/web/index.php(21): yii\base\Application->run()
#12 {main}
```

**Comment by emarthinsen** [comment]
Here's a long version:

```
2018-05-31 18:47:51 [172.20.0.1][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_ (time: 1.244s). Output:
Exception: Undefined index: fields (/var/app/vendor/firstborn/migrationmanager/src/services/EntriesContent.php:93)
#0 /var/app/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/app/vendor...', 93)
#1 /var/app/vendor/firstborn/migrationmanager/src/services/EntriesContent.php(93): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/app/vendor...', 93, Array)
#2 /var/app/vendor/firstborn/migrationmanager/src/services/BaseMigration.php(134): firstborn\migrationmanager\services\EntriesContent->importItem(Array)
#3 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(280): firstborn\migrationmanager\services\BaseMigration->import(Array)
#4 /var/app/migrations/m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_.php(89): firstborn\migrationmanager\services\Migrations->import(Array)
#5 /var/app/vendor/craftcms/cms/src/db/Migration.php(56): craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_->safeUp()
#6 /var/app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_))
#8 /var/app/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#9 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#10 /var/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/app/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('migrations', Array)
#13 /var/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#14 /var/app/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('migrationmanage...', Array)
#15 /var/app/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('migrationmanage...', Array)
#16 /var/app/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/app/web/index.php(21): yii\base\Application->run()
#19 {main}

2018-05-31 18:47:51 [172.20.0.1][1][-][error][craft\errors\MigrationException] yii\base\ErrorException: Undefined index: fields in /var/app/vendor/firstborn/migrationmanager/src/services/EntriesContent.php:93
Stack trace:
#0 /var/app/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/app/vendor...', 93)
#1 /var/app/vendor/firstborn/migrationmanager/src/services/EntriesContent.php(93): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/app/vendor...', 93, Array)
#2 /var/app/vendor/firstborn/migrationmanager/src/services/BaseMigration.php(134): firstborn\migrationmanager\services\EntriesContent->importItem(Array)
#3 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(280): firstborn\migrationmanager\services\BaseMigration->import(Array)
#4 /var/app/migrations/m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_.php(89): firstborn\migrationmanager\services\Migrations->import(Array)
#5 /var/app/vendor/craftcms/cms/src/db/Migration.php(56): craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_->safeUp()
#6 /var/app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_))
#8 /var/app/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#9 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#10 /var/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/app/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('migrations', Array)
#13 /var/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#14 /var/app/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('migrationmanage...', Array)
#15 /var/app/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('migrationmanage...', Array)
#16 /var/app/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/app/web/index.php(21): yii\base\Application->run()
#19 {main}

Next craft\errors\MigrationException: An error occurred while executing the "craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_ migration: Undefined index: fields in /var/app/vendor/craftcms/cms/src/db/MigrationManager.php:260
Stack trace:
#0 /var/app/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m180531_211655_migration_entry_privacy_home_terms_of_service_hardware_hardware_peripherals_hardware_13_inch_touchscreen_peripherals_hardware_support_heat_spreader_support_support_revision_history_))
#1 /var/app/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#2 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#3 /var/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /var/app/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('migrations', Array)
#6 /var/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#7 /var/app/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('migrationmanage...', Array)
#8 /var/app/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('migrationmanage...', Array)
#9 /var/app/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/app/web/index.php(21): yii\base\Application->run()
#12 {main}
```

**Comment by emarthinsen** [comment]
I'll bet I know what it is. I have a few content items that I haven't yet assigned any fields too. Just a hunch.

**Comment by emarthinsen** [comment]
Yup. That was it. I changed line 93 of EntriesContent.php to:

`$entry->setFieldValues(array_key_exists('fields', $value) ? $value['fields'] : []);`

and the migration worked. I'm not sure if this is the best place to do it or if it would be better to emit an empty array for the `fields` index when the data is exported. Either way, hope this info is useful.

**Comment by fb-derrick-grigg** [comment]
Thanks @emarthinsen, nice catch. Try latest release.

**Comment by rlabardee** [comment]
I get the same exact error, but on `BaseContentMigration.php:385` 

```
2018-12-11 09:55:12 [-][1][-][error][craft\errors\MigrationException] yii\base\ErrorException: Undefined index: fields in /vendor/firstborn/migrationmanager/src/services/BaseContentMigration.php:385
Stack trace:
#0 /vendor/firstborn/migrationmanager/src/services/EntriesContent.php(87): firstborn\migrationmanager\services\EntriesContent->localizeData()
#1 /vendor/firstborn/migrationmanager/src/services/EntriesContent.php(81): firstborn\migrationmanager\services\EntriesContent->importItem()
#2 /vendor/firstborn/migrationmanager/src/services/BaseMigration.php(147): firstborn\migrationmanager\services\EntriesContent->importItem()
#3 /vendor/firstborn/migrationmanager/src/services/Migrations.php(280): firstborn\migrationmanager\services\EntriesContent->import()
#4 /migrations/m181210_131900_migration_entry_best_buy_projects_etsy_projects_hp_projects_enernoc_projects_bank_of_america_projects_projects.php(46): firstborn\migrationmanager\services\Migrations->import()
#5 /vendor/craftcms/cms/src/db/Migration.php(56): craft\contentmigrations\m181210_131900_migration_entry_best_buy_projects_etsy_projects_hp_projects_enernoc_projects_bank_of_america_projects_projects->safeUp()
#6 /vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\contentmigrations\m181210_131900_migration_entry_best_buy_projects_etsy_projects_hp_projects_enernoc_projects_bank_of_america_projects_projects->up()
#7 /vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp()
#8 /vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations()
#9 /vendor/yiisoft/yii2/base/InlineAction.php(57): firstborn\migrationmanager\controllers\RunController->actionMigrations()
#10 /vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#11 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#12 /vendor/craftcms/cms/src/web/Controller.php(104): firstborn\migrationmanager\controllers\RunController->runAction()
#13 /vendor/yiisoft/yii2/base/Module.php(528): firstborn\migrationmanager\controllers\RunController->runAction()
#14 /vendor/craftcms/cms/src/web/Application.php(282): craft\web\Application->runAction()
#15 /vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction()
#16 /vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
#17 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#18 /web/index.php(20): craft\web\Application->run()
#19 {main}
```

I worked around it for now by deleting my exiting content and re-running the migration.
