### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Michael-Reich** [Firstborn/Craft-Migration-Manager#45]
Since the new Updates of Craft I constantly getting.

**Status:** A fatal error has occurred: Status: Internal Server Error

This is from the log:

```
2019-01-25 06:26:48 [-][1][-][error][application] [
    'Could not save the blog field.',
    'Could not save the modules field.',
]
2019-01-25 06:26:48 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply m190125_061324_migration_field_blog_modules (time: 0.060s). Output:

2019-01-25 06:26:48 [-][1][-][error][craft\errors\MigrationException] craft\errors\MigrationException: An error occurred while executing the "craft\contentmigrations\m190125_061324_migration_field_blog_modules migration. in /home/forge/ddd/vendor/craftcms/cms/src/db/MigrationManager.php:260
Stack trace:
#0 /home/forge/ddd/vendor/firstborn/migrationmanager/src/services/Migrations.php(326): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m190125_061324_migration_field_blog_modules))
#1 /home/forge/ddd/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#2 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#3 /home/forge/ddd/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/forge/ddd/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/forge/ddd/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrations', Array)
#6 /home/forge/ddd/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#7 /home/forge/ddd/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('migrationmanage...', Array)
#8 /home/forge/ddd/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('migrationmanage...', Array)
#9 /home/forge/ddd/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /home/forge/ddd/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/forge/ddd/web/index.php(21): yii\base\Application->run()
#12 {main}
2019-01-25 06:26:46 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/migrationmanager/run/migrations'
]
```

**Comment by dgrigg** [comment]
@Michael-Reich yes, it's an issue with the latest Craft release. Working on fixes at this moment.

**Comment by Michael-Reich** [comment]
@dgrigg Great thank you! Tell me if you are ready! :)

**Comment by Michael-Reich** [comment]
@dgrigg Could you fix it, can we help something?

**Comment by dgrigg** [comment]
Should have the fix ready tomorrow. It ended up being more involved than I expected.

**Comment by dgrigg** [comment]
@Michael-Reich try the latest release 3.0.16
